### ISSUE TITLE
java.lang.RuntimeException: RESOURCE_EXHAUSTED: GraknBackendException-Index overlap has led to the accidental sharing of a partially complete vertex

### ISSUE THREAD

**Issue by xMAnton** [xMAnton/BioGrakn#2]
**Client side**

$ java -jar BuildBioGrakn.jar 

Building BioGrakn v1.4.2 ...

Importing NCBI Gene ........................ done
Importing Gene Ontology ....................... done
Importing Gene2GO ............................ done
Importing miRBase .................................. done
Importing Reactome ...................... done
Importing Reactome2GO ............ done
Importing Reactome2miRNA ...................... done
Importing miRCancer ............... done
Importing Uniprot SwissProt .................... done
Importing Uniprot2Reactome ... done

Importing miRNASNP ............Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at it.cnr.icar.biograkn.BuildBioGrakn.main(BuildBioGrakn.java:108)
	... 5 more
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: RESOURCE_EXHAUSTED: GraknBackendException-Index overlap has led to the accidental sharing of a partially complete vertex {v[548352144]}. Please check server logs for the stack trace.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at it.cnr.icar.biograkn.MiRNASNP.importer(MiRNASNP.java:100)
	... 10 more
Caused by: java.lang.RuntimeException: RESOURCE_EXHAUSTED: GraknBackendException-Index overlap has led to the accidental sharing of a partially complete vertex {v[548352144]}. Please check server logs for the stack trace.
	at ai.grakn.client.Grakn$Transaction.responseOrThrow(Grakn.java:218)
	at ai.grakn.client.Grakn$Transaction.query(Grakn.java:234)
	at ai.grakn.client.executor.RemoteQueryExecutor.lambda$streamConceptMaps$3(RemoteQueryExecutor.java:97)
	at java.lang.Iterable.spliterator(Iterable.java:101)
	at ai.grakn.client.executor.RemoteQueryExecutor.streamConceptMaps(RemoteQueryExecutor.java:98)
	at ai.grakn.client.executor.RemoteQueryExecutor.run(RemoteQueryExecutor.java:73)
	at ai.grakn.graql.internal.query.InsertQueryImpl.stream(InsertQueryImpl.java:81)
	at ai.grakn.graql.Query.execute(Query.java:60)
	at it.cnr.icar.biograkn.MiRNASNP.lambda$0(MiRNASNP.java:85)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1618)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Server logs**

`2018-10-11 11:41:40,375 [grpc-default-executor-1] ERROR a.g.e.r.SessionService$TransactionListener - Runtime Exception in RPC TransactionListener: 
ai.grakn.exception.TemporaryWriteException: Index overlap has led to the accidental sharing of a partially complete vertex {v[548352144]}
        at ai.grakn.exception.TemporaryWriteException.indexOverlap(TemporaryWriteException.java:56)
        at ai.grakn.kb.internal.concept.ElementFactory.buildConcept(ElementFactory.java:155)
        at ai.grakn.kb.internal.concept.ElementFactory.buildConcept(ElementFactory.java:146)
        at ai.grakn.kb.internal.EmbeddedGraknTx.getConcept(EmbeddedGraknTx.java:356)
        at ai.grakn.kb.internal.concept.AttributeTypeImpl.attribute(AttributeTypeImpl.java:153)
        at ai.grakn.kb.internal.concept.AttributeTypeImpl.lambda$putAttribute$3(AttributeTypeImpl.java:131)
        at ai.grakn.kb.internal.concept.TypeImpl.putInstance(TypeImpl.java:100)
        at ai.grakn.kb.internal.concept.AttributeTypeImpl.putAttribute(AttributeTypeImpl.java:131)
        at ai.grakn.kb.internal.concept.AttributeTypeImpl.create(AttributeTypeImpl.java:116)
        at ai.grakn.graql.internal.query.executor.ConceptBuilder.putInstance(ConceptBuilder.java:415)
        at ai.grakn.graql.internal.query.executor.ConceptBuilder.tryPutConcept(ConceptBuilder.java:247)
        at ai.grakn.graql.internal.query.executor.ConceptBuilder.build(ConceptBuilder.java:184)
        at ai.grakn.graql.internal.query.executor.QueryOperationExecutor.buildConcept(QueryOperationExecutor.java:270)
        at ai.grakn.graql.internal.query.executor.QueryOperationExecutor.get(QueryOperationExecutor.java:401)
        at ai.grakn.graql.internal.pattern.property.HasAttributeProperty.lambda$insert$1(HasAttributeProperty.java:151)
        at ai.grakn.graql.internal.pattern.property.PropertyExecutor.execute(PropertyExecutor.java:76)
        at ai.grakn.graql.internal.query.executor.QueryOperationExecutor.insertAll(QueryOperationExecutor.java:253)
        at ai.grakn.graql.internal.query.executor.QueryOperationExecutor.insertAll(QueryOperationExecutor.java:110)
        at ai.grakn.graql.internal.query.executor.QueryExecutorImpl.lambda$runMatchInsert$2(QueryExecutorImpl.java:94)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at org.apache.tinkerpop.gremlin.process.traversal.Traversal.forEachRemaining(Traversal.java:265)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at ai.grakn.graql.internal.query.executor.QueryExecutorImpl.runMatchInsert(QueryExecutorImpl.java:94)
        at ai.grakn.graql.internal.query.executor.QueryExecutorImpl.run(QueryExecutorImpl.java:82)
        at ai.grakn.graql.internal.query.InsertQueryImpl.stream(InsertQueryImpl.java:81)
        at ai.grakn.engine.rpc.SessionService$TransactionListener.query(SessionService.java:237)
        at ai.grakn.engine.rpc.SessionService$TransactionListener.handleRequest(SessionService.java:142)
        at ai.grakn.engine.rpc.SessionService$TransactionListener.lambda$onNext$0(SessionService.java:117)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Could not determine the base type of vertex [Vertex [V548352144] /nProperty [INDEX] value [ATTRIBUTE-mirStart-20513370] /nProperty [ID] value [V548352144] /nProperty [THING_TYPE_LABEL_ID] value [177] /nProperty [VALUE_LONG] value [20513370] /n]
        at ai.grakn.kb.internal.concept.ElementFactory.getBaseType(ElementFactory.java:249)
        at ai.grakn.kb.internal.concept.ElementFactory.buildConcept(ElementFactory.java:153)
        ... 41 common frames omitted`

**Comment by xMAnton** [comment]
Source code: 

https://github.com/xMAnton/BioGrakn/blob/1.4.2/src/main/java/it/cnr/icar/biograkn/MiRNASNP.java

**Comment by xMAnton** [comment]
It seems to be fixed reducing the thread pool size from 8 to 4.
